### ISSUE TITLE
Switch Pro Controller

### ISSUE THREAD

**Issue by jflatby** [ylorant/splitty#15]
So I use the Switch Pro Controller on emulator in Windows. Has been working fine, but the first time I clicked a button on the controller after opening Splitty in Chrome, it automatically connected to the splitter, and a blue light appeared around the home button. The controller now works in splitty, but no other programs on my computer detect any input.. Not the emulator, and not even windows' input-test-thing in bluetooth settings. I've tried removing the bluetooth device, quitting Splitty, and adding the device again, but it now always goes automatically into the state with the blue light.. Splitty can detect it but no other programs as far as I know..

**Comment by jflatby** [comment]
Fixed by restarting computer.. duh
Don't know why I didn't try that before posting. But oh well, now you know.

**Comment by ylorant** [comment]
Happy to see that your problem was fixed. Sorry for not having replied earlier.
