### ISSUE TITLE
Specific Gamepad Button Bindings

### ISSUE THREAD

**Issue by Squishy6094** [ylorant/splitty#17]
I'm having a small problem with the Gamepad button bindings that is I can't map Start and Reset to the same button without having Split mapped to that button, You could possibly fix it by having each action be a different mapping instead of having Start/Split and Stop/Reset.

**Comment by ylorant** [comment]
Hello,

I'm having a problem with the asked behavior. You see, the gamepad bindings are made as an alternative to the actions you see on the main timer page, but there is no separate "start" and "split" action. Doing so would require to rework a non-trivial bit of code in the project, and to be frank, I'm not really maintaining it anymore (for now ? I don't know man, I have so much stuff lying around).

I may or may not do it in an indefinite future (who knows) but if it is a very important feature, you can do it yourself and do a pull request that I'll be happy to review.

Regards.
