### ISSUE TITLE
It's not obvious what a "Timer" is

### ISSUE THREAD

**Issue by CryZe** [ylorant/splitty#4]
Splitty seems to differentiate between the Timer Name and the Game Name and it's far from obvious what the difference is. Most other Timers simply either use a single field to describe the splits or split it into Game Name and Category Name. It doesn't look like the "Timer Name" is the Category Name though, so it's pretty confusing what this is supposed to mean. I'd suggest changing that or making it clear to the user what you are meaning with that.

**Comment by ylorant** [comment]
You're right, I will add a mention for both I think. It allows someone to have multiple timers for the same run.

**Comment by ylorant** [comment]
I added a tooltip feature in commit d3d0cb8. It will surely be expanded later.
